name: PHPUnit Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        php_ver:
          - "8.2"
          - "8.3"
        wp_ver:
          - "latest"
        wc_ver:
          - "10.4.3"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Install subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_ver }}
          tools: phpunit, composer

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Run install-wp-tests.sh
        run: ./tests/bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wp_ver }}

      - name: Run install-woocommerce.sh
        run: ./tests/bin/install-woocommerce.sh ${{ matrix.wc_ver }}

      - name: Run phpunit
        run: ./vendor/bin/phpunit -c phpunit.xml
        env:
          WC_VERSION: ${{ matrix.wc_ver }}
